### ISSUE TITLE
Xcode 6.2

### ISSUE THREAD

**Issue by appsforall** [aumentia/VSAumentiaIOS#4]
Hi Guys,
I'm trying to get the demo project running with Xcode 6.2 ( no beta, regular version), but I only see these errors. Any solution? Would really like to use your SDK!

ld: warning: ignoring file HelloVisualSearch/SDK/VS.framework/VS, missing required architecture x86_64 in file HelloVisualSearch/SDK/VS.framework/VS (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Roi", referenced from:
      objc-class-ref in ViewController.o
  "_OBJC_CLASS_$_vsPlugin", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Regards!
Wim

**Comment by aumentia** [comment]
Hi Wim - The SDK won't work on iOS Simulator. Please select an iOS device to build the project.

**Comment by appsforall** [comment]
got it. works on my device indeed.
