### ISSUE TITLE
Swift?

### ISSUE THREAD

**Issue by appsforall** [aumentia/VSAumentiaIOS#5]
Hi guys! Do you already have any sample code in swift, or only objective C for now?

**Comment by aumentia** [comment]
Hi - Only ObjC by now.

**Comment by aumentia** [comment]
Added Swift support:
https://github.com/aumentia/HelloVisualSearch_iOS/wiki/Connect-to-SWIFT
https://github.com/aumentia/HelloMotionDetectSwift
